export const staticLeads = [
  {
    _id: "lead_1",
    id: "lead_1",
    name: "Alex Morgan",
    company: "TechFlow Solutions",
    phone: "+1 (555) 234-5678",
    email: "alex@techflow.io",
    website: "https://techflow.io",
    source: "Website",
    budget: "450000",
    priority: "Hot",
    status: "New",
    followUpCount: 3,
    follow: "2026-08-20",
    nextAction: "Demo Call",
    assignedTo: "emp_1",
    assignedEmployee: "emp_1",
    notes: "Interested in enterprise CRM migration.",
  },
  {
    _id: "lead_2",
    id: "lead_2",
    name: "Samantha Wright",
    company: "Apex Global Logistics",
    phone: "+1 (555) 876-5432",
    email: "swright@apexglobal.com",
    website: "https://apexglobal.com",
    source: "LinkedIn",
    budget: "1200000",
    priority: "Hot",
    status: "In Progress",
    followUpCount: 5,
    follow: "2026-08-18",
    nextAction: "Proposal Review",
    assignedTo: "emp_2",
    assignedEmployee: "emp_2",
    notes: "Requires custom API integrations.",
  },
  {
    _id: "lead_3",
    id: "lead_3",
    name: "David Chen",
    company: "Quantum Digital Labs",
    phone: "+1 (555) 345-6789",
    email: "david.c@quantumlabs.org",
    website: "https://quantumlabs.org",
    source: "Referral",
    budget: "350000",
    priority: "Warm",
    status: "Contacted",
    followUpCount: 2,
    follow: "2026-08-22",
    nextAction: "Follow-up Email",
    assignedTo: "emp_1",
    assignedEmployee: "emp_1",
    notes: "Wants cloud infrastructure consulting.",
  },
  {
    _id: "lead_4",
    id: "lead_4",
    name: "Elena Rostova",
    company: "Vanguard Financial",
    phone: "+1 (555) 987-6543",
    email: "elena@vanguardfin.com",
    website: "https://vanguardfin.com",
    source: "Google Search",
    budget: "850000",
    priority: "Hot",
    status: "Converted",
    followUpCount: 4,
    follow: "2026-08-15",
    nextAction: "Contract Signed",
    assignedTo: "emp_3",
    assignedEmployee: "emp_3",
    notes: "Converted to enterprise tier.",
  },
  {
    _id: "lead_5",
    id: "lead_5",
    name: "Marcus Sterling",
    company: "BioHealth Innovations",
    phone: "+1 (555) 456-7890",
    email: "msterling@biohealth.net",
    website: "https://biohealth.net",
    source: "Event/Exhibits",
    budget: "200000",
    priority: "Cold",
    status: "New",
    followUpCount: 1,
    follow: "2026-08-25",
    nextAction: "Send Brochure",
    assignedTo: "emp_2",
    assignedEmployee: "emp_2",
    notes: "Met at TechExpo 2026.",
  },
];

export const staticEmployees = [
  {
    _id: "emp_1",
    id: "emp_1",
    uid: "emp_1",
    name: "Ragavi M",
    role: "Senior Sales Lead",
    email: "ragavi@pearlsithub.com",
    phone: "+91 98765 43210",
    department: "Sales",
    status: "Active",
    type: "onTrack",
    taskScore: "14/15",
    performance: "92%",
  },
  {
    _id: "emp_2",
    id: "emp_2",
    uid: "emp_2",
    name: "Karthik Raja",
    role: "Full Stack Lead",
    email: "karthik@pearlsithub.com",
    phone: "+91 98765 12345",
    department: "Engineering",
    status: "Active",
    type: "onTrack",
    taskScore: "13/15",
    performance: "88%",
  },
  {
    _id: "emp_3",
    id: "emp_3",
    uid: "emp_3",
    name: "Priya Sharma",
    role: "UI/UX Designer",
    email: "priya@pearlsithub.com",
    phone: "+91 98765 67890",
    department: "Design",
    status: "Active",
    type: "onTrack",
    taskScore: "15/15",
    performance: "95%",
  },
  {
    _id: "emp_4",
    id: "emp_4",
    uid: "emp_4",
    name: "Suresh Kumar",
    role: "Account Executive",
    email: "suresh@pearlsithub.com",
    phone: "+91 98765 54321",
    department: "Sales",
    status: "Active",
    type: "AtRisk",
    taskScore: "10/15",
    performance: "74%",
  },
];

export const staticClients = [
  {
    _id: "client_1",
    companyName: "TechFlow Solutions",
    headquarters: "San Francisco, CA",
    contactPerson: "Alex Morgan",
    email: "alex@techflow.io",
    phone: "+1 (555) 234-5678",
    status: "Active",
    priority: "High",
    budget: 1500000,
    paid: 1200000,
    pending: 300000,
    health: "94%",
    managers: ["Ragavi M", "Karthik Raja"],
    dueDate: "2026-12-31",
  },
  {
    _id: "client_2",
    companyName: "Apex Global Logistics",
    headquarters: "New York, NY",
    contactPerson: "Samantha Wright",
    email: "swright@apexglobal.com",
    phone: "+1 (555) 876-5432",
    status: "Active",
    priority: "High",
    budget: 2800000,
    paid: 2000000,
    pending: 800000,
    health: "88%",
    managers: ["Ragavi M", "Priya Sharma"],
    dueDate: "2026-11-15",
  },
  {
    _id: "client_3",
    companyName: "Quantum Digital Labs",
    headquarters: "Austin, TX",
    contactPerson: "David Chen",
    email: "david.c@quantumlabs.org",
    phone: "+1 (555) 345-6789",
    status: "Active",
    priority: "Medium",
    budget: 950000,
    paid: 950000,
    pending: 0,
    health: "98%",
    managers: ["Karthik Raja"],
    dueDate: "2026-10-20",
  },
  {
    _id: "client_4",
    companyName: "Vanguard Financial",
    headquarters: "Chicago, IL",
    contactPerson: "Elena Rostova",
    email: "elena@vanguardfin.com",
    phone: "+1 (555) 987-6543",
    status: "Active",
    priority: "High",
    budget: 4200000,
    paid: 3000000,
    pending: 1200000,
    health: "91%",
    managers: ["Ragavi M", "Suresh Kumar"],
    dueDate: "2026-12-15",
  },
];

export const staticProjects = [
  {
    _id: "proj_1",
    id: "proj_1",
    title: "TechFlow Enterprise CRM Migration",
    company: "TechFlow Solutions",
    status: "In Progress",
    progress: 78,
    priority: "High",
    dueDate: "2026-09-30",
    members: ["emp_1", "emp_2", "emp_3"],
  },
  {
    _id: "proj_2",
    id: "proj_2",
    title: "Apex Logistics Automated Tracking System",
    company: "Apex Global Logistics",
    status: "In Progress",
    progress: 45,
    priority: "High",
    dueDate: "2026-10-15",
    members: ["emp_1", "emp_2"],
  },
  {
    _id: "proj_3",
    id: "proj_3",
    title: "Quantum Labs AI Analytics Dashboard",
    company: "Quantum Digital Labs",
    status: "Completed",
    progress: 100,
    priority: "Medium",
    dueDate: "2026-07-31",
    members: ["emp_2", "emp_3"],
  },
  {
    _id: "proj_4",
    id: "proj_4",
    title: "Vanguard Payment Gateway Integration",
    company: "Vanguard Financial",
    status: "In Progress",
    progress: 60,
    priority: "High",
    dueDate: "2026-11-30",
    members: ["emp_1", "emp_3", "emp_4"],
  },
];

export const staticTasks = [
  {
    id: "task_1",
    title: "Redesign onboarding flow for enterprise clients",
    company: "TechFlow Solutions",
    assignedTo: "emp_1",
    assignedEmployee: "emp_2",
    status: "In Progress",
    priority: "Hot",
    dueDate: "2026-08-25",
    progress: 65,
  },
  {
    id: "task_2",
    title: "Setup automated email sequences for new signups",
    company: "Apex Global Logistics",
    assignedTo: "emp_3",
    assignedEmployee: "emp_1",
    status: "Pending",
    priority: "Warm",
    dueDate: "2026-08-28",
    progress: 20,
  },
  {
    id: "task_3",
    title: "Fix payment webhooks payload parsing issue",
    company: "Vanguard Financial",
    assignedTo: "emp_2",
    assignedEmployee: "emp_1",
    status: "Completed",
    priority: "Hot",
    dueDate: "2026-08-15",
    progress: 100,
  },
  {
    id: "task_4",
    title: "Conduct security audit for API endpoints",
    company: "Quantum Digital Labs",
    assignedTo: "emp_4",
    assignedEmployee: "emp_2",
    status: "In Progress",
    priority: "Cold",
    dueDate: "2026-09-05",
    progress: 40,
  },
];

export const staticFollowups = [
  {
    _id: "fol_1",
    clientName: "Alex Morgan",
    companyName: "TechFlow Solutions",
    type: "Demo Call",
    assignedTo: "Ragavi M",
    followupTime: "10:30 AM",
    status: "Pending",
    date: "2026-08-18",
  },
  {
    _id: "fol_2",
    clientName: "Samantha Wright",
    companyName: "Apex Global Logistics",
    type: "Proposal Review",
    assignedTo: "Ragavi M",
    followupTime: "02:00 PM",
    status: "Scheduled",
    date: "2026-08-18",
  },
  {
    _id: "fol_3",
    clientName: "David Chen",
    companyName: "Quantum Digital Labs",
    type: "Contract Discussion",
    assignedTo: "Karthik Raja",
    followupTime: "04:15 PM",
    status: "Completed",
    date: "2026-08-17",
  },
  {
    _id: "fol_4",
    clientName: "Elena Rostova",
    companyName: "Vanguard Financial",
    type: "Onboarding Call",
    assignedTo: "Suresh Kumar",
    followupTime: "11:00 AM",
    status: "Completed",
    date: "2026-08-16",
  },
];

export const staticAttendance = [
  {
    _id: "att_1",
    employee_uid: "emp_1",
    attendanceState: "working",
    clockIn: new Date().toISOString(),
    login_photo: "https://i.pravatar.cc/100?img=1",
  },
  {
    _id: "att_2",
    employee_uid: "emp_2",
    attendanceState: "working",
    clockIn: new Date().toISOString(),
    login_photo: "https://i.pravatar.cc/100?img=2",
  },
  {
    _id: "att_3",
    employee_uid: "emp_3",
    attendanceState: "break",
    clockIn: new Date().toISOString(),
    login_photo: "https://i.pravatar.cc/100?img=3",
  },
  {
    _id: "att_4",
    employee_uid: "emp_4",
    attendanceState: "clocked_out",
    clockIn: new Date().toISOString(),
    login_photo: "https://i.pravatar.cc/100?img=4",
  },
];

export const staticHolidays = [
  {
    holidayName: "Independence Day",
    holidayDate: "2026-08-15",
    holidayType: "National",
  },
  {
    holidayName: "Vinayaka Chaturthi",
    holidayDate: "2026-09-14",
    holidayType: "Festival",
  },
  {
    holidayName: "Gandhi Jayanti",
    holidayDate: "2026-10-02",
    holidayType: "Gazetted",
  },
];
